### ISSUE TITLE
gbk file missing from output

### ISSUE THREAD

**Issue by ceya** [tseemann/prokka#179]
Hi, 

Does anyone know why prokka cannot return any gbk output? Here's the error message I got:

Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.11 from http://www.vicbioinformatics.com' -Z 103a\/103a_06262016\.err -i 103a\/103a_06262016\.fsa 2> /dev/null

Thanks!
Brooke

**Comment by bretonics** [comment]
Prokka comes with the `tbl2asn` binary under `prokka/binaries/linux/` (assuming you are on a *nix system, the last directory will vary). You likely don't have it installed and it's not being sourced from the prokka binaries folder.

Type `which tbl2asn` and if you have sourced it properly, it will output the location (/path-to/prokka/binaries/linux/tbl2asn). 

Otherwise you might want to source it like `ln -s /path-to/prokka/binaries/linux/tbl2asn /usr/local/bin`. That's what I have done rather than source it a my `.bashrc` or `.bash_profile`

**Comment by ceya** [comment]
i installed tbl2asn again and here's the output error:
[18:45:43] Running: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.11 from http://www.vicbioinformatics.com' -Z IRTtest2\/IRT_06292016\.err -i IRTtest2\/IRT_06292016\.fsa 2> /dev/null
[18:45:43] Deleting unwanted file: IRTtest2/errorsummary.val
[18:45:43] Deleting unwanted file: IRTtest2/IRT_06292016.dr
[18:45:43] Deleting unwanted file: IRTtest2/IRT_06292016.fixedproducts
[18:45:43] Deleting unwanted file: IRTtest2/IRT_06292016.ecn
[18:45:43] Deleting unwanted file: IRTtest2/IRT_06292016.val
[18:45:43] Repairing broken .GBK output that tbl2asn produces...
[18:45:43] Running: sed 's/COORDINATES: profile/COORDINATES:profile/' < IRTtest2\/IRT_06292016\.gbf > IRTtest2\/IRT_06292016\.gbk
sh: IRTtest2/IRT_06292016.gbf: No such file or directory
[18:45:43] Could not run command: sed 's/COORDINATES: profile/COORDINATES:profile/' < IRTtest2\/IRT_06292016\.gbf > IRTtest2\/IRT_06292016\.gbk

is it because the tbl2asn didn't install properly?

**Comment by bretonics** [comment]
So now it seems `tbl2asn` is working since your error is not running the `tbl2asn` command but rather after it runs. @tseemann can provide more information, as he knows the program better, but I'll try to keep helping meanwhile.

What do you get on your terminal when you type these two commands:

    which tbl2asn
    which sed

It might be the output of `tbl2asn` is not what it's suppose to be. Also, how are you running `prokka`?

**Comment by ceya** [comment]
Here's the output from which:

~/prokka-1.11/bin/tbl2asn
/bin/sed

Here's my command to run prokka:
prokka --outdir IRTtest2 --locustag IRT IRT.fasta
The other output files (gff faa) look fine

Thank you very much for your suggestion!

**Comment by mherold1** [comment]
Refering to this (https://github.com/tseemann/prokka/issues/164) and similar issues I would suggest checking if your fasta header contain pipe characters. 
Also it is good to be aware that the tbl2asn binary expires after a year (https://github.com/tseemann/prokka/issues/139), which might have been the initial problem.

**Comment by bretonics** [comment]
@ceya, ok, so now that you took care of re-installing `tbl2asn` and your original error is gone, but now the `sed` command doesn't work, the most likely cause (as @mherold1 mentioned) is that your FASTA headers contain `|` characters. I had the same issue and removing them fixes the problem. 

Check my issue #164. You should be good from now on.

**Comment by ceya** [comment]
@bretonics @mherold1 
my fasta headers don't contain  |. they are all in the format of >strain_#

**Comment by mherold1** [comment]
Then I can only suggest to get more information on why tbl2asn fails to produce the .gbf file:
Either copy the tbl2asn command and run it separately:
'tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.11 from http://www.vicbioinformatics.com' -Z IRTtest2\/IRT_06292016.err -i IRTtest2\/IRT_06292016.fsa'
or remove the '2> /dev/null' in that line in the bin/prokka script temporarily and run it as usual.

**Comment by bretonics** [comment]
Wild guess (past experiences), I wonder if it might have any hidden Windows special characters that cause it to fail. What system are you running it in? More precisely, were your FASTA files created in Windows and uploaded to a Unix system?

**Comment by ceya** [comment]
@bretonics 
Yes. I created headers in Windows and uploaded them to linux for analysis

**Comment by bretonics** [comment]
Aha! Another reason why I hate Windows. You need to change the file format because Windows screws everything up. Edit your files on the Linux machine using `vi fileName`. Then press colon the `:` and enter "set ff=unix" and hit enter, then save and quit using `:wq`.

Hopefully that's your problem, Windows formatted files with their incompatible hidden special character syntax!

**Comment by ceya** [comment]
@bretonics Yes that was the reason! Thank you sooo very much!

**Comment by bretonics** [comment]
@ceya gladly!

**Comment by tseemann** [comment]
You can also use `dos2unix dodgyfile.fasta` to fix it.
