### ISSUE TITLE
Use of ¦ in FASTA header of *.fna file stops ENA submission

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/prokka#212]
I use the FNA files produced by Prokka to submit assemblies to ENA, but this doesn't work (anymore) due to the ¦ symbol in the FASTA header of the FNA file. This is what ENA sent me:

_During the validation process of your submitted files the following problems were detected:
ERROR: The ENA genomes assembly parser reads the contig names until it find the first '|', then does not consider the rest of the line.
In your files this results in all contigs having the same name:
>gnl
and this brings up an error so the assembly processing stops._

Is the header required like that for Genbank submission, or is it dispensable/can be disabled?

**Comment by tseemann** [comment]
@dutchscientist 
That header is what Genbank requires.... *sigh*

It's often just easier to submit your reads and CONTIGS and let NCBI annotate with PGAAP. Since Dec 2015 they became very strict and I am struggling to pass their requirements. I can probably do it my dumbing down Prokka annotation, but that seems silly.

Torsten

**Comment by dutchscientist** [comment]
Hi Torsten,

no worries, I expected something like that. I use ENA as this is simpler to do batch upload (Genbank sucks for that).

Maybe worth adding a comment about this to the documentation on GitHub, so people are aware of it?

cheers
Arnoud
