### ISSUE TITLE
Why exclude CDS's that are being overlapped by RNA?

### ISSUE THREAD

**Issue by alexblex1** [tseemann/prokka#238]
Hello, 

I am an intern currently working on a project that uses Prokka to annotate a large amount of genomes. While comparing the speed of Prokka to it's annotation software alone, Prodigal, I saw that Prokka excluded a few CDS's. When looking through the logs I saw that they were excluded due to the fact that either RNA overlaps them, or the CDS's overlap RNA. 

My question is, why does Prokka exclude these CDS's? With my current knowledge, I don't see any reason for that to occur, a singular CDS could code for many things. If there is literature or some source that talks of why these CDS's should be excluded, that'd be even more appreciated.

**Comment by tseemann** [comment]
@alexblex1 The CDS are predicted first and have higher priority.  Then RNA are predicted. The rRNA and tRNA should not overlap a CDS. In rare cases they might, but it's more likely a false positive tRNA. Those RNAs are highly conserved and essential to the cell so I don't think they would tolerate harbouring a CDS. 

You can disable this with:
```
  --cdsrnaolap      Allow [tr]RNA to overlap CDS (default OFF)
```

However ncRNAs are a different story. They should be able to exist over a CDS usually in the opposite strand (anti-sense).  I do NOT include those in the overlapping exclusion rules, as they may be predicted when using `--rfam`.

Do you have an example of a tRNA or rRNA that has a functional coding region as part of it?

**Comment by hlfreund** [comment]
Hi there. I am running my assembled contigs from my metagenomes through Prodigal without binning them beforehand (I am more interested in functional pool rather than who is producing what). I noticed that all of my CDSs were "excluded" due to their overlap with tRNA or CRISPR regions. Should I employ the --cdsrnaolap flag so this does not happen? 

Currently the program is still running so I am hoping that the annotations are successful, but I wanted to ask about the --cdsrnaolap flag. Thanks so much!
