### ISSUE TITLE
Invalid genbank files in case of long sequence ids

### ISSUE THREAD

**Issue by rattei** [tseemann/prokka#249]
Annotation of scaffolds from spades asssemblies results in invalid genbank files:

LOCUS       NODE_1_length_187937_cov_36.2375187937 bp   DNA linear

Please either rename the sequences or raise an error message to the user.

Thanks,
Thomas

**Comment by tseemann** [comment]
@rattei What version of Prokka are you using? This is an error to the user for last 2 years.

```
[14:36:17] Loading and checking input file: longname.fna
[14:36:17] Contig ID must <= 37 chars long: NODE_1_length_187937_cov_36.2375187937
[14:36:17] Please rename your contigs OR try '--centre X --compliant' to generate clean contig names.
```

**Comment by rattei** [comment]
We are using prokka 1.12, installed by May from GitHub. This is supposed to be the latest version.

Thomas

**Comment by rattei** [comment]
How to reproduce with attached file mssa.fna:
prokka mssa.fna
head -1 PROKKA_08062017/PROKKA_08062017.gbk 
LOCUS       NODE_1_length_2778945_cov_67.56232778945 bp   DNA linear
[mssa.fna.zip](https://github.com/tseemann/prokka/files/1202891/mssa.fna.zip)

**Comment by rattei** [comment]
I confirm the options --centre X --compliant solve the problem. However, without these options I did not get any of the error messages you have mentioned. With the --quiet option, no messages at all are shown to the user.

Have absolutely no idea what kind of "user_error" should have happened here.

**Comment by tseemann** [comment]
@rattei i have had some confusion here, yes.  The contig name length is only checked when you use `--compliant`. If you don't want compliant files, you get back what you put in.  The GFF3 and FASTA files are all perfectly valid with any contig ID length. It's only GBK which is the problem.

THat's the crux of the issue. If you put in normal contig names, ALL output files are fine. if you put in long ones and don't use `--compliant`, you get ALL output files being good EXCEPT for GBK. I'm stuck between a rock and a hard place here. 

I could print a warning but I feel it will be lost in all the log output Prokka produces. If you think that would help, I can add it?

I don't recommend using GBK as an output format anymore because of these restrictions on it, and the `tbl2asn` dependency which I would like to remove.  These issues with GBK have been the cause of *many* issues in Prokka, and I have lost sleep over it.

**Comment by rattei** [comment]
Hi Torsten, thanks for spending your Saturday on this issue!

I agree that the gbk format complicates things a lot. However, for e.g. loading the annotations into the MAUVE aligner, it is really useful.

Regarding the long contig names: a clear warning in the end of the prokka output about the non-compliant genbank format in case of long contig names would definitely do it.

Cheers,
Thomas

**Comment by tseemann** [comment]
@rattei I think we should be asking @koadman to support GFF3 format in Mauve.

**Comment by koadman** [comment]
Hi guys, I would love to have GFF3 support in Mauve! There is a lot of bitrot that needs patching up as well, I am trying to figure out how to carve out the time needed for the effort... Maybe someone can launch a journal called Nature Bitrot Remediation so the uni admins can grasp the importance of this kind of work?

**Comment by tolot27** [comment]
At the end of 2018 NCBI announced the extended accession format and recommend [Adapting flatfile parsers for GenBank’s new accession formats](https://ncbiinsights.ncbi.nlm.nih.gov/2018/12/03/adapting-flatfile-parsers-genbank-new-accession-formats/). This format change allows slightly longer contig names (up to 20 characters). SPAdes often still produces longer contig names like the following example shows:

```
LOCUS       NODE_1_length_1310770_cov_113.2391310770 bp   DNA linear
08-MAY-2019
```

Here, prokka (v1.13.3) introduces another error by wrapping the date to the next line. Downstream programs like Mauve cannot deal with either of these problems and need to be fixed as well.

@koadman I'm happy to contribute Mauve, but best here at GitHub. See our mail correspondence.

**Comment by tseemann** [comment]
@tolot27 thanks for the info about the new accession formats.

Prokka is not introducing that error, that is `tbl2asn` which is NCBI's own software, which I call.
