### ISSUE TITLE
Prokka: NCBI prokaryotic genome submission, mobile element re-annotation & tbl2asn 

### ISSUE THREAD

**Issue by ABTsutenkyo** [tseemann/prokka#272]
Hello!

First of all, thank you very much for your tool, it's great (and the code is a delight to read). 

I'm currently trying to submit a complete genome containing a mobile genomic island (ICE) to Genbank via data processing with Prokka (after failing miserably to use RAST/tbl2asn on my own). 

I know that it is not yet possible to annotate mobile elements with Prokka (issue #258), so I annotated my ICE manually (direct *.gbk editing). However I then need to re-generate the *.asn/*.sqn file for the NCBI submission. I manually updated the *.tbl, but I find myself unable to re-generate the correct *.asn/*.sqn file using tbl2asn separately, using this command : 
`./tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -Z ./projectFolder/ -i completeGenome.fsa`
My output seems to miss the annotation bit.     

If I'm not missing anything, tbl2asn is supposed to take in input the *.tbl and the *.fsa (unlike table2asn_GFF, also from the NCBI, requiring the *.gff), right? Does your code take something else in input that I can't generate separately? (@seq for example?)

I would very much like your help and insights on the matter, 
(I'm beginning to have nightmares about genome submission...)

Kind Regards,
Audrey B.

**Comment by tseemann** [comment]
Audrey / @ABTsutenkyo 

I did not even know `tbl2asn_GFF` even existed!  

The bad news I have for you is that since December 2015, NCBI made submission more strict. Many people are unable to get Prokka/RAST annotations into  NCBI.  I think NCBI doesn't really want them anymore, as they will re-annotated everything with their PGAP assembler and put it in Refseq.

Your best strategy is to just submit the contigs and ✔️ the box for "PGAP Assembly?".

What you are trying to do is reasonable, but NCBI have made it far too difficult to do this.  You can use their web interface to submit it, and upload the TBL file and then add the ICE element using their web interface, or do it via SEQUIN software.

I'm sorry I don't have good new for you, but I ran out of energy to fight with their system anymore.
