### ISSUE TITLE
Prokka calls many short CDS

### ISSUE THREAD

**Issue by lfaller** [tseemann/prokka#278]
Hi all,

I recently used prokka to annotate a bacillus species. I noticed there were more CDS called by prokka than what NCBI estimates this organism should have. Prokka annotated 5050 CDS, whereas NCBI estimates this species has about 3751 CDS.

Looking at a density plot of CDS sequence lengths, prokka seems to call more short CDS:

![combined_density_plot](https://user-images.githubusercontent.com/7854149/35757735-829a7114-083e-11e8-9763-3c954391af11.png)

Do you have any thoughts on why Prokka calls so many more short CDS regions? Do I need to tune certain parameters? Or is NCBI overly conservative?

Any feedback is appreciated!
Cheers,
~Lina

**Comment by andersgs** [comment]
Hi @lfaller.

How confident are you that you have a single species or even isolate sequenced? I have seen CDS inflation when my sequence data is contaminated with a different species or a rather distinct strain from the one I originally expected. 

The assembly may also be an issue. If you have a fairly fragmented assembly, you may have a bunch of what appear to be pseudogenes being called or multiple copies of genes occurring because you have more than one genome. 

Those would be my first two places to look. 

You could use Roary along with a couple of NCBI isolates to see if you get some chunk of CDS's that are not shared across the Bacilus isolates. I would also try Kraken on your sample, to see if there is significant contamination from other species.

Finally, you could try to annotate the NCBI isolate with Prokka to see if you get similar or very different results. 

That does not necessarily answer your question. But, my experience with Prokka is that with good data, it tends to identify the expected number of CDS for the species without too much fuss (give or take a few CDS).

Good luck! 

Anders.

**Comment by tseemann** [comment]
@lfaller if you have a poor genome assembly (ie. lots of contigs) then you will get  lots of small spurious genes called.  if its a 454/Pacbio/IonTorrent genome this will be made worse by hompolymers causing frame-shifts, putting lots of genes into 2 pieces.

**Comment by jotes35** [comment]
Hi All,

I have a similar issue and I would like some advice.

I performed annotation on my sample which is a Mycobacterium isolate using the Agy99.gb as my proteins. The command I used is _prokka --cpus 15 --kingdom Bacteria --prefix sample --genus Mycobacterium --rfam --species ulcerans --cdsrnaolap --metagenome --proteins Agy99.gb sample.fasta _

I then counted the CDS(using biopython on the prokka generated genebank file) and got 8665.
I decided to further test with the Agy99 fasta as well. So I annotated the Agy99.fasta using Agy99.gb as proteins. I got 5315

I also counted the original Agy99.gb and I got 4160.

For my sample I understand factors such as contamination might have led to the high CDS count. But what I am confused about is why prokka will give different CDS count for Agy99.fasta after annotating with its own genebank 

Below is the result in summary
mysample 8665
prokka genereted Agy99 genebank 5315
original Agy99 genebank 4160
