### ISSUE TITLE
Feature request: allow prodigal single mode for <100kbp sequences

### ISSUE THREAD

**Issue by zachcp** [tseemann/prokka#292]
Hi Torsten,

Thank you for Prokka.

I have been noticing small differences in the ORF calling between Prokka and Prodigal that seems to be due to the `$prodigal_mode` set on [line 703](https://github.com/tseemann/prokka/blob/master/bin/prokka#L703).  It seems to me that if your target sequence is less than 100kbp you will be sent into `meta` mode regardless of whether or not you have used the `--metagenome` CLI option.  For cosmid sequencing I would like to be able to use `single` mode on sequences less than 100kbp.

Would it be possible to change the default behavior or allow for a CLI override?

Thanks,
zach cp

**Comment by tseemann** [comment]
I remember specifically changing it to `meta` mode because of problems with prodigal for sequences < 100 kbp. I can't seem to find it in the commit history at the moment, but I believe there was insufficient DNA for prodigal to train itself properly.  The `meta` mode overcame this limitation.

Maybe something has changed since then. I don't really know. But i recall i did it for a good reason at the time. I will consider adding a `--prodigal_opt` option in the next version. But as that could be 12 months away, you will just have to manually edit the line(s) below:

```
my $prodigal_mode = ($totalbp >= 100000 && !$metagenome) ? 'single' : 'meta';
my $cmd = "prodigal -i \Q$outdir/$prefix.fna\E -c -m -g $gcode -p $prodigal_mode -f sco -q";
```
