### ISSUE TITLE
At which position should a CDS start

### ISSUE THREAD

**Issue by a1204350** [tseemann/prokka#300]
Hi it's me again,

I recently noticed that prokka preferred to start from the 2nd ATG or the 2nd start codon (e.g. amino acid V) compared with NCBI Prokaryotic Annotation Pipeline.

I annotated a plasmid using both NCBI and prokka, and found out a same CDS annotated by prokka was nearly always shorter than that of NCBI annotation. I took a look at the missing part and turned out it was the sequence between the 1st and 2nd start codon (a few bases away, same reading frame).

So, which one is more likely to be true?

Thanks much,

Yu

**Comment by a1204350** [comment]
I did use codon scheme 11 for bacteria

**Comment by tseemann** [comment]
@a1204350 Prokka is just a pipeline. It uses Prodigal to call genes. I can't change how it does it. Start codons are difficult. Both could be right - many genes have multiple RBS and start positions.  You need experimental evidence (RNA and Prot) to really know.  Just because it is in NCBI doesn't mean it is correct BUT i would trust PGAP more than Prokka.

Sorry I can't be of more help.
