### ISSUE TITLE
Phage sequences

### ISSUE THREAD

**Issue by juulluu21** [tseemann/prokka#324]
Does Prokka also annotate phage regions present in the bacterial genome?

**Comment by tseemann** [comment]
No.

It would be good to, but PHASTER does not have a standalone version.

It could be possible to use the web service interface but that would need to be negotiated with the authors as it would put a huge load on their server.

So no plans to support it just yet, but I am considering it.

**Comment by avilella** [comment]
Hi @tseemann and @juulluu21 , I am working on a project to annotate assembled phage sequences and also find phage regions inside bacterial genomes. I found out that PHASER is unavailable due to maintenance, what alternatives are there for this task?
https://bioinformatics.stackexchange.com/questions/9286/alternatives-to-phaster-phage-annotation-server
