### ISSUE TITLE
Error in the gff output file (prokka version 1.12)

### ISSUE THREAD

**Issue by Juke34** [tseemann/prokka#338]
We figured out many problems in the gff file output from the Prokka version 1.12. Consequently the format is invalid and cannot be really used in other tools.

1) The mRNA feature lacks a parent attribute.
2) CDS have 2 parent features, and one of them is the gene feature when only the mRNA feature is expected.
3) tRNA have mRNA as parent feature while a tRNA is expecting to have a gene as parent feature.
4) A minor thing but it's a bit awkward, it's having the CDS feature before the mRNA and the gene in the file.

Related to those problems I'm not sure the convertion to EMBL with [gff3toembl](https://github.com/sanger-pathogens/gff3toembl) script still does the job. I guess it's the same with the [EMBLmyGFF3](https://github.com/NBISweden/EMBLmyGFF3).

**Comment by andrewjpage** [comment]
Have you considered using this other tool? It was built to convert GFF files from Prokka into EMBL format and was used to submit over 20,000 assemblies to the EMBL:

http://joss.theoj.org/papers/10.21105/joss.00080

It's unclear what you mean by 'the format is invalid'? Are you saying that your software cannot parse the file because it has hard coded a eukaryotic gene model?

**Comment by Juke34** [comment]
By invalid I mean the gff3 produced by prokka 1.12 doesn't follow the [format specification].(https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md).

I was just saying that it could be problematic for other tools to use this gff. And it would be important for this tool so widely used to create a proper gff output.


That being said,  I did some tests this morning:
Artemis => it complains about some stuff but succeed to deal properly with it.
EMBLmyGFF3 => it doesn't complain but the python parser duplicate the features. So you end-up with twice much more features than expected.
I have tried to test gff3toembl but didn't succeed due to problems with Genometools. I guess it's working fine otherwise we would have seen people complaining but I would be interested to have confirmation that gff3toembl is working fine with this gff output.

**Comment by tseemann** [comment]
@Juke34 Prokka uses the GFF format that NCBI uses for bacterial genomes. This is *different* to the "standard" GFF gene model of gene->mRNA->exons->CDS because we don't have exons/introns. It's designed to be compatible  with the standard bacterial Genbank format (.gbk.gbff) too. I do understand how the true GFF model works in eukaryotic datasets (although its usually GTF/GFF2.5 not 3.0).

Because Prokka doesn't have mRNA features those bugs must be coming from elsewhere. I only produce CDS by default, but gene can be generated by `--genes` option too, to conform to what NCBI prefers.  But as CDS == gene for nearly every bacterial gene in Genbank (no one annotates UTRs) it is overload for most bacterial genome pipelines.

**Comment by Juke34** [comment]
Thank you for your input @tseemann.
You're right it is related to the option --addgenes and --addmrna. The colleague that sent me the file confirmed  me he has used those options. 
We usually don't use those options and post process the data to make it fully gff3 compliant file using our own tool. 

To summarize the gff3 file produced by default is correct but becomes slightly wrong when using the --add genes and/or --add mrna options  (only the format is touched because the structural and functional annotation itself is not affected).
 
P.S: Our gff3 parser deals with refseq format that doesn't contain any mRNA feature. So using the --addgenes option would haven't raised any problem. So I conclude it is the option --addmrna that have been introduced in the version 1.12 that creates unexpected gff-like file when activated.
