### ISSUE TITLE
Does prokka still include TIGRFAMs and how does prkka end up with the ec_number?

### ISSUE THREAD

**Issue by coralzhang** [tseemann/prokka#340]
Hi, 
I am new to prokka and I want to annotate my metagenomics contigs from de novo assembly using prokka. In the ideal case, I just want to search the TIGRFAMs database. So my question is 
(1) Does prokka still include TIGRFAMs?
(2) If yes, can I include the TIG number in the output? If not, could anyone please help me figure out how to set up a custom database?
(3) How does how does prokka end up with the ec_number as I see in the output gff file?
(4) I know that the --listdb option could list the database. But can I know, for example, the version of Uniport is compiled?

Thanks!

Xinlian

**Comment by tseemann** [comment]
0. Prokka is not really designed for metagenomic annotation, because it is often very fragmented and partial genes are not handled well.

1. No it doesn't include TIGRFAMs aymore because the database is too large for Github. But you can put the TIGRFAMS.hmm file in the `hmm` folder and run `--setupdb` and it should work.

2. It will put the HMM accession number in the `/evidence` tag.  There is documentation in the prokka README.md that explains how to do custom databases.

3. EC_number is also explained in the custom database section of the manual. You need to provide it.

4. I do not have any support for recording the database versions.  They are custom filtered by me first before putting in Prokka. See the manual.

**Comment by coralzhang** [comment]
Thank you very much for the response. But my input is assembled contigs/bins, which in the ideal case should be just a draft genome of a bacteria. Is this okay, then?

**Comment by tseemann** [comment]
Yes that should be ok, but it will still be a "bad" draft genome compared to sequencing and assembling an isolate.
