### ISSUE TITLE
--rnammer not working

### ISSUE THREAD

**Issue by greboul** [tseemann/prokka#360]
Hi,
I used prokka using the flag --rnammer but in the log file I saw that barrnap has been used instead.
I used the prokka 1.12
Can you explain or fix that?
Thanks

![prokka_screenshot](https://user-images.githubusercontent.com/13840904/51534035-e465d880-1e44-11e9-87a0-33a7daa600c0.png)

**Comment by jvollme** [comment]
I think you need to install rnammer yourself and add it to your PATH. This is probably because, although rnammer is free, the developers want you to agree with their license term before allowing you to use it. Therefore it cannot simply be bundled with prokka.

You can get rnammer [here](http://www.cbs.dtu.dk/cgi-bin/sw_request?rnammer)

But beware, there are a few nuisances when installing (rnammer has not been updated in a while and some of the dependencies changed). You have to make sure to have hmmer2 installed and the path it's binaries set in the rnammer script. It will NOT work with hmmer3 (it will just yield empty results with the new versions).

Also you likely have to delete all instances of "--cpu=1" from the core-rnammer script. 
Details on these problems and on how to solve them are given [here](https://blog.karinlag.no/2013/10/rnammer-install/) (rnammer is still my favorite rRNA-gene finder though. Really hope they'll release an updated version of it sometime)

**Comment by tseemann** [comment]
Thanks @jvollme for helping out on this issue!
