### ISSUE TITLE
Issue Installing using Conda

### ISSUE THREAD

**Issue by ivanjm422** [tseemann/prokka#362]
Hi, I'm attempting to install prokka using conda and after what appears to be a successful installation, i get the following error when running prokka: 

`Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /anaconda3/bin/../perl5 /opt/conda/envs/prokka_env/lib/perl5/site_perl/5.22.0 /anaconda3/lib/perl5/site_perl/5.22.0/darwin-thread-multi-2level /anaconda3/lib/perl5/site_perl/5.22.0 /anaconda3/lib/perl5/5.22.0/darwin-thread-multi-2level /anaconda3/lib/perl5/5.22.0 .) at /anaconda3/bin/prokka line 27.
BEGIN failed--compilation aborted at /anaconda3/bin/prokka line 27.
`

Please let me know if there is anything else I should do to get it to work. Thanks!

**Comment by stonyc** [comment]
How did you install prokka, and by extension Perl? If you installed Perl previously (and not through conda, perhaps through apt-get, etc.), then that can typically cause issues with programs trying to resolve environment variables... especially programs that you install through different package management systems.

If you installed Perl previously (and not through conda), then I would suggest the following:

1) removing your existing installation of Perl (you can look here for an example: [https://www.howtoinstall.co/en/ubuntu/trusty/perl?action=remove](url)),
2) since you're familiar with conda, then let conda manage your packages as much as possible to avoid problems like this in the future,
3) furthermore, I would highly recommend making use of conda virtual environments:

# Create the environment, add the bioconda channel as a source to search for packages:
`conda create -c bioconda -n test prokka`
# Activate the environment:
`conda activate test`
# Run prokka:
`do stuff`
# Exit the environment when done:
`conda deactivate`

Here's a snippet of what you should expect with conda installing the XML::Simple module automagically for you:

 
`perl-xml-sax-expat:                  0.51-pl526_2               bioconda`
`perl-xml-sax-writer:                   0.57-pl526_0               bioconda`
`perl-xml-simple:                       2.25-pl526_0               bioconda`
`perl-xml-twig:                         3.52-pl526_1               bioconda`
`perl-xml-writer:                       0.625-pl526_2              bioconda`
`perl-xml-xpath:                        1.44-pl526_0               bioconda `

The advantage to using conda environments, like pip virtualenvs, is that you can silo your workspaces effectively and down the line share your code and analyses with others more efficiently as well.

**Comment by ivanjm422** [comment]
Thank you so much! That works great! Now when i try to read in a fasta file, i get a "____.fasta is not a readable non-empty FASTA file. 

Should the file be in a specific spot for prokka to read it? Sorry about the confusion, I'm a beginner at this.

**Comment by ivanjm422** [comment]
That worked, Thanks a ton! Please disregard the deleted reply, my directory was set wrong and the program is running fine now.

**Comment by stonyc** [comment]
You're welcome, glad it works.

**Comment by tseemann** [comment]
Thanks @stonyc - I appreciate you helping fellow prokka users!
