### ISSUE TITLE
Misannotation and force amino acid sequence generation

### ISSUE THREAD

**Issue by pixuenan** [tseemann/prokka#388]
Hi,

When I use Prokka version 1.13.3 to annotate _Helicobacter pylori_ genome 26695 (complete). I found several misannotation, for example HP0487. In NCBI annotation, it locates at 510965-512407 (you can find it in the gff file under the NCBI folder). However, Prokka misannotated it as 26695_00502 locates at 511010-512407, and the sequence of it in the `.ffn` file starts with "TTG". So 45bp of the beginning of the gene lost, as the cross-check with the NCBI sequence suggested. Moreover, in the Prokka annotated `.faa` file, the amino acid sequence of 26695_00502 starts with "M", and actually if I change the first T of the 26695_00502 nucleotide sequence in the `.ffn` file to A , then the translated amino acid sequence is identical to the 26695_00502 incorrect aa sequence in the `.faa` file. This also happened to 26695_00503. 

The command I used is as following:
```
prokka --locustag 26695 --outdir {params.folder} --prefix 26695 \
GCF_000008525.1_ASM852v1_genomic.fna --centre X --compliant --addgenes --genus \
Helicobacter --species pylori --usegenus --force --proteins \
GCF_000008525.1_ASM852v1_genomic.gbff --cpus {threads}
```
[26695_annotation.zip](https://github.com/tseemann/prokka/files/3285442/26695_annotation.zip)

In the attachment, you can find NCBI annotation result and Prokka result, also the genome sequence.
Any help will be appreciated.

**Comment by nigyta** [comment]
Dear pixuenan,

The start position of the CDS sometimes varies depending on the gene prediction tool that is used, when multiple candidates for the start codon exist.
Therefore, this is a problem of Prodigal rather than Prokka.
Even in the NCBI database, there are discrepancies in the start positions of protein sequences. It is not easy to tell which one is correct without careful consideration.

With regard to the start codon "TTG", the Prokka's behaviour is correct.
In a bacterial genome, TTG is used as an alternative start codon although not so common. Normally TTG is translated to Leu, but when used as a start codon, it is translated to Met (more precisely to fMet).

**Comment by pixuenan** [comment]
Thank for the clarification!

**Comment by tseemann** [comment]
Thanks for the good explanation @nigyta !

**Comment by Buuntu** [comment]
I have seen this as well @pixuenan and @nigyta where there are several start codons.  Would using your own genus or protein database with good annotations get around this or is Prodigal still going to be the bottleneck? I don't know if the --genus or --proteins flag is just for the annotation portion or if Prokka can use these to assign ORFs as well.
