### ISSUE TITLE
Problem with the version of makeblastdb

### ISSUE THREAD

**Issue by djung0928** [tseemann/prokka#390]
Hello,

I'm totally new to use Prokka and have been using Ubuntu on Windows 10 to try to install Prokka. But I've been struggling with the installation. My ubuntu keeps saying the version of makeblastdb is 2.6 even though 2.8 is applied. 

[16:54:55] Appending to PATH: /home/djung0928/prokka/bin/../binaries/linux
[16:54:55] Appending to PATH: /home/djung0928/prokka/bin/../binaries/linux/../common
[16:54:55] Appending to PATH: /home/djung0928/prokka/bin
[16:54:55] Cleaning databases in /home/djung0928/prokka/db
[16:54:55] Cleaning complete.
[16:54:55] Looking for 'makeblastdb' - found /usr/bin/makeblastdb
[16:54:58] Determined makeblastdb version is 2.6
[16:54:58] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.

I deleted the directory and tried it again but it is still same...Is there any solution for this issue?

Thanks very much in advance

**Comment by tasbd4** [comment]
@tseemann 
Could you please give a solution? I'm facing the same issue since 16 days
this problem appears when I try to setup database. 

prokka --setupdb
[22:32:50] Appending to PATH: /home/student-mns/prokka/bin/../binaries/linux
[22:32:50] Appending to PATH: /home/student-mns/prokka/bin/../binaries/linux/../common
[22:32:50] Appending to PATH: /home/student-mns/prokka/bin
[22:32:50] Cleaning databases in /home/student-mns/prokka/db
[22:32:50] Cleaning complete.
[22:32:50] Looking for 'makeblastdb' - found /usr/bin/makeblastdb
[22:32:50] Determined makeblastdb version is 2.6
[22:32:50] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.

**Comment by tseemann** [comment]
Which version of Prokka are you using?   Type `prokka --version`

Also, it seems you are depending on the bundled binaries that come with prokka. It is better to install the blast 2.8 binaries yourself from the NCBI download site.

**Comment by dnbaker** [comment]
I can reproduce this with a local build on Ubuntu 16.04 LTS, as a newer version (2.8 required by Prokka@master). I imagine an install fresh from NCBI is the right way to move forward.

**Comment by tseemann** [comment]
Ok great news!

**Comment by juliofdiaz** [comment]
I am trying to install Prokka on a server where there is makeblastdb v. 2.2 installed. This is the version that is accessible through the $PATH. I have the binaries for makeblastdb v. 2.9 in a non-admin folder. Is there a way to specify the path to my makeblastdb v. 2.9, so that I don't have to change the default makeblastdb install.

**Comment by montoyah** [comment]
@juliofdiaz, you're better off installing conda/miniconda, create a virtual environment for Prokka, and install all your dependencies and their versions there. That way yo don't have to worry abouth paths and system-wide dependencies conflicts.

**Comment by tseemann** [comment]
@juliofdiaz 
```
PATH=/path/to/blast-2.9/bin:$PATH prokka -h
```

**Comment by yuziliang1** [comment]
> I can reproduce this with a local build on Ubuntu 16.04 LTS, as a newer version (2.8 required by Prokka@master).
> 
> Downloading executables from ncbi solved the problem.

prokka --setupdb
  I didn't solve the problem, I want to know how to Prokka needs makeblastdb 2.2 or higher. Please upgrade and try again.

**Comment by LuoDaTou123** [comment]
Open prokka(env)/bin/prokka
Find 
  'makeblastdb' => {
    GETVER  => "makeblastdb -version",
    REGEXP  => qr/makeblastdb:\s+($BIDEC)/,
    MINVER  => "2.2",
    NEEDED  => 0,  # only if --proteins used
  }
Then chang   MINVER  => "2.2"  TO   MINVER  => "2.1" 
Run again is OK!

**Comment by marade** [comment]
I keep running into this bug with Conda environments, but only part of the time (?) Looking at the code it seems version comparisons are being done in ways that won't always work. In addition to the error reported above for the issue, I get this too:

Argument "1.7.8" isn't numeric in numeric lt (<) at /home/ubuntu/miniconda3/envs/py39/bin/prokka line 253.

A framework for comparing version strings seems appropriate for addressing this:

https://perlmaven.com/how-to-compare-version-numbers-in-perl-and-for-cpan-modules
