### ISSUE TITLE
Can I ask prokka to only produce the gbk file?

### ISSUE THREAD

**Issue by MolyWang** [tseemann/prokka#430]

**Comment by tseemann** [comment]
There is no way to currently disable it except by editing the `prokka` script and deleting or commenting out the `run_cmd("tbl2asn .....");` lines.

**Comment by tseemann** [comment]
Sorry i mis-read your question.
You _only_ want the GBK file?
No, but I just run prokka then delete all the files I don't want.

**Comment by mlbonatelli** [comment]
Hi :) I was wondering if it still not possible to disable the production of the _.gbk_ file through the command line. That would be really convenient for me because I am using **prokka** on a server. Thanks 😊

**Comment by andersgs** [comment]
Hi @mlbonatelli. Your question seems to be the opposite of what is asked in this issue. 

But, if I understand correctly, the easy thing would be to do something like this:

```bash
prokka --outdir tmp contigs.fa && rm -f tmp/*.gbk
```
That will remove your gbk after it is made...

Is your concern about disk space on the server? Or cpu?

**Comment by mlbonatelli** [comment]
Hi @andersgs,

You are absolutely right, it is the opposite. I am only writing in this closed issue because @tseemann said something about deleting the line in the script responsible to generate the _.gbk_ file.

The problem is that I am using `prokka` to annotate a metagenome and it is taking days to finish, and I can see that is because it is generating the _.gbk_ file. Since I am running on a server, I don't have privileges to modify the script, that is why I wondered if I could just use a command on `prokka` to not produce the _.gbk_ file.

If I just interrupt `prokka` in this last step, will it somehow compromise the other files?

**Comment by andersgs** [comment]
I am not that confident that `prokka` should be used for metagenomic datasets. 

But, GBK is the last file produced by `prokka` and interrupting it won't affect the other output. 

The other option is, if your server has conda, is to create your own conda prokka environment. You can then edit the script to comment out the appropriate line.

Best of luck.

**Comment by andersgs** [comment]
I have not tried it, so have no idea how well it works, but if you have not tried it, it may be worth giving ATLAS a go: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03585-4

**Comment by mlbonatelli** [comment]
Thanks for the reply @andersgs :) I will check with my collaborators, it was their suggestion to usa `prokka` to annotate the metagenome. And thanks for the link to ATLAS!
