### ISSUE TITLE
'Kp30660NJST2581.fasta' is not a readable non-empty FASTA file in prokka docker

### ISSUE THREAD

**Issue by kenken86** [tseemann/prokka#465]
I use prokka in docker when I try to run:
docker run staphb/prokka:latest prokka --outdir /Users/kenken/Desktop/BM Kp30660NJST2581.fasta 
It came up like this. I'm sure that my file is a fasta file.  I try everything that post on internet but it's not working.
[03:26:55] This is prokka 1.14.5
[03:26:55] Written by Torsten Seemann <torsten.seemann@gmail.com>
[03:26:55] Homepage is https://github.com/tseemann/prokka
[03:26:55] Local time is Tue Feb 25 03:26:55 2020
[03:26:55] You are not telling me who you are!
[03:26:55] Operating system is linux
[03:26:55] You have BioPerl 1.006924
[03:26:55] System has 2 cores.
[03:26:55] Option --cpu asked for 8 cores, but system only has 2
[03:26:55] Will use maximum of 2 cores.
[03:26:55] Annotating as >>> Bacteria <<<
[03:26:55] 'Kp30660NJST2581.fasta' is not a readable non-empty FASTA file

**Comment by tseemann** [comment]
I am not a docker expert, but maybe you need to "bind" the `/Users/kenken/Desktop/` folder to the docker container so it can read `/Users/kenken/Desktop/BM Kp30660NJST2581.fasta` ?

**Comment by kapsakcj** [comment]
@kenken86 You will need to use the `-v` flag with `docker run` to mount a volume from your host file system to the container file system

If your reference is in your $PWD, then something like this should work: 
```
# mount your $PWD to the /data directory that is in the container's filesystem
docker run -v $PWD:/data staphb/prokka:latest prokka --outdir /data/prokka-output /data/Kp30660NJST2581.fasta
```
With the above command, your prokka results will end up at `$PWD/prokka-output`

Some more tips/tricks can be found here for running docker containers https://staph-b.github.io/docker-builds/run_containers/

**Comment by tseemann** [comment]
Thank you @kapsakcj !

**Comment by kyoreth** [comment]
Same issue here, tried mounting with -v but no luck. Not sure if a docker issue or a prokka issue or a permissions issue.. should be fine permissions wise, it has read permissions on all folders at the very least. Fasta file doesn't seem to have any issues, seqkit for example recognises it fine.

**Comment by kyoreth** [comment]
I also tried running prokka on the example file from the github repo, but no go there either.

**Comment by kapsakcj** [comment]
@kyoreth could you please post the command you used? PATHs are a bit tricky in docker, so I'm thinking might be the issue. 

I was able to run the test file using this command:
```
$ docker run --rm -v $pwd:/data staphb/prokka:latest prokka --cpus 4 --outdir /data/prokka-out /prokka-1.14.5/test/plasmid.fna
[12:48:11] This is prokka 1.14.5
[12:48:11] Written by Torsten Seemann <torsten.seemann@gmail.com>
[12:48:11] Homepage is https://github.com/tseemann/prokka
[12:48:11] Local time is Tue May 19 12:48:11 2020
[...]
[12:49:53] Annotation finished successfully.
[12:49:53] Walltime used: 0.12 minutes
[12:49:53] If you use this result please cite the Prokka paper:
[12:49:53] Seemann T (2014) Prokka: rapid prokaryotic genome annotation. Bioinformatics. 30(14):2068-9.
[12:49:53] Type 'prokka --citation' for more details.
[12:49:53] Share and enjoy!
```

As mentioned above ^^ I usually specify one directory as the input and output directory inside the container: `/data`. This doesn't apply since the test data is packaged with prokka, but if I were passing in my own assembly that's in my $pwd on my local computer, then I would specify it's path as `/data/my-assembly.fasta` inside the container

**Comment by kyoreth** [comment]
@kapsakcj Thanks for the reply! Your example command runs fine, but I can't seem to locate the output. As for using my own file, still no luck. It definitely seems to be something with docker paths..For example, I have a folder in my home folder with the file 'myfasta'. I'd like to run prokka on it. 

docker run -v $pwd:/ staphb/prokka:latest prokka --outdir /prokka-out myfasta

This fails, but I'm thinking its because the path is wrong, so prokka can't find the file. Is /data a special location in relation to the docker container?

**Comment by kyoreth** [comment]
@kapsakcj Figured it out! The command I ended up using was:
docker run -v $PWD:/data  staphb/prokka:latest prokka --cpus 4 --outdir /data/prokka-out /data/FUNCT_ANNOT/myfasta

**Comment by kapsakcj** [comment]
👏 🎆 Awesome!
