### ISSUE TITLE
Reference genome annotation

### ISSUE THREAD

**Issue by ireneortega** [tseemann/prokka#486]
Hi!

I annotated a reference genome, NCTC 11168, using a reference proteins file downloaded from NCBI https://www.ncbi.nlm.nih.gov/nuccore/AL111168 (using --proteins). I found that some genes are not well annotated, even the genome I am annotating is the same from which the reference proteins are taken. For example, comparing with reference gene Cj1564/CAL35661/Q0P864, PROKKA annotates 

"MNSIKIKLSLIANLIAIFALIVLGIVSFYFTKTSLYESTLKNQT
                     DLLKVTQSTVEDFRSTNQSFTRALEKDIANLPYQSLITEENIINNVGPILKYYRHSIN
                     ALNVYLGLNNGKVLLSQKSNDAKMPELRDDLDIKTKDWYQEALKTNDIFVTPAYLDTV
                     LKQYVITYSKAIYKDGKIIGVLGVDIPSEDLQNLVAKTPGNTFLFDQKNKIFAATNKE
                     LLNPSIDHSPVLNAYKLNGDNNFFSYKLNNEERLGACTKVFAYTACITESADIINKPI
                     YKAAFIQAIVVIIVVVFSVILLYFIVSKYLSPLAAIQTGLTSFFDFINYKTKNVSTIE
                     VKSNDEFGQISNAINENILATKRGLEQDNQAVKESVQTVSVVEGGNLTARITANPRNP
                     QLIELKNVLNKLLDVLQARVGSDMNAIHKIFEEYKSLDFRNKLENASGSVELTTNALG
                     DEIVKMLKQSSDFANALANESGKLQTAVQSLTTSSNSQAQSLEETAAALEEITSSMQN
                     VSVKTSDVITQSEEIKNVTGIIGDIADQINLLALNAAIEAARAGEHGRGFAVVADEVR
                     KLAERTQKSLSEIEANTNLLVQSINDMAESIKEQTAGITQINDSVAQIDQTTKDNVEI
                     ANESAIISSTVSDIANNILEDVKKKRF"
 
and the first aminoacids MLKITKIKRKI are not annotated. PROKKA forgets this part of the protein! I think PROKKA shouldn't make this mistakes and so, I can't trust other genome annotations. How can I solve this problem?

Thanks for your help.

**Comment by tseemann** [comment]
@ireneortega as explained in the prokka paper, prokka identifies its genes _ab initio_ using Prodigal. It then uses a database to assign function. It makes no attempt to identify the "correct" start codon. What you observe is (unfortunately) expected behaviour some of the time. Plans for prokka 2.x include a full glocal alignment of `--proteins` to try and get exact annotations, but 1.x does not support that. There may be other genome annotation tools that do - perhaps RAST or BASYS or DFAST ?
