### ISSUE TITLE
problem with tbl2asn

### ISSUE THREAD

**Issue by tivdnbos** [tseemann/prokka#511]
Hi,

When running prokka:
`prokka --metagenome --cpus 30 --outdir /my_project/prokka/COM_06/ --prefix COM_06 /my_project/megahit-output/COM_06/final.contigs.fa`

It always get stuck at the tbl2asn search:
`Could not run command: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.14.6 from https://github.com/tseemann/prokka' -Z \/my_project\/prokka\/COM_06\/\/COM_06\.err -i \/my_project\/prokka\/COM_06\/\/COM_06\.fsa 2> /dev/null`

Any idea how to resolve this?

Best,
Tim

**Comment by kapsakcj** [comment]
You'll likely need to update/upgrade your `tbl2asn` installation since it expires. I believe the `tbl2asn` binary that is included with the most recent version of prokka (`prokka/binaries`) works with no issues.

This is a frequently encountered issue: https://github.com/tseemann/prokka/issues?q=is%3Aissue+tbl2asn

**Comment by tivdnbos** [comment]
Thanks! It didn´t work, but I solved it with installing the ncbi tools separately.
