### ISSUE TITLE
Max. contig ID length

### ISSUE THREAD

**Issue by mherold1** [tseemann/prokka#76]
First of all thanks for the new version.
I noticed that you introduced $MAXCONTIGIDLEN to check for long contig names. 
Is it intended that this is also checked if `--compliant` option is not set?
So if I have a contig with ID e.g. : "gi|479173639|ref|NC_021021.1|" downloaded from NCBI this is longer than 20 and I have to rename it by setting `--locustag` and `--centre` to something short.

**Comment by aleimba** [comment]
Hi @mherold1,
**--locustag** and **--centre** have no consequence on the FASTA ID line in the **.fsa* file, the ID is directly parsed from the input FASTA file. The **.fsa* file is used in NCBI's `tbl2asn` to create the final **.gbk*, **.sqn* etc. files. This is where `$MAXCONTIGIDLEN` comes in, because the GenBank format is very strict and if the original ID is too long it interferes with the contig length info in the GenBank header (see issue #32).

You can use e.g. `sed` to get rid of everything besides the accession number:
```bash
sed -r 's/^>gi\|[0-9]+\|ref\|(.+)\|/>\1/' -i file.fna
```

HTH,
Andreas

**Comment by mherold1** [comment]
Thanks for your reply and the link to #32, which I hadn't seen before. 

I just noticed from the error message: 
`[14:33:14] Contig ID must <= 20 chars long: gi|479173639|ref|NC_021021.1|
[14:33:14] Please rename your contigs or use --centre XXX to generate clean contig names. `

If I only set --centre is set (e.g. --centre X) it still fails as : `gnl|X|PROKKA_contig000001` is still too long?

If I also set --locustag to X, contig IDs become X_contig000001... in the .gbk file. 

An alternative is of course to change contig-names beforehand like you mentioned.

**Comment by aleimba** [comment]
yes, you're totally right. I was wrong in my post before. If **--centre** is set, the \*.fsa FASTA ID is put together from either **--locustag**, **--prefix**, **--outdir**, or **--strain** (in that order). Sorry about that, don't know where I was looking before ...
So yes for your current situation, either set **--center** or change your initial FASTA IDs (shameless plug, I have a very small script for numerating contigs in FASTA IDs: https://github.com/aleimba/bac-genomics-scripts/tree/master/rename_fasta_id).

But you definitely found a bug, because in the new Prokka version `$MAXCONTIGIDLEN` is now too strict. I'm guessing, @tseemann meant to set only the contig ID (which is used for LOCUS in the \*.gbk file) to a maximum of 20, not the whole FASTA ID (with "gnl|center|\<contig_ID\>") ...

It says here (http://www.ncbi.nlm.nih.gov/genomes/static/Annotation_pipeline_README.txt) under **FILES  TO BE SUBMITTED**, that:

    NOTE: The |center|<ID1> part of the header must be less than 38 characters

With an \<contig_ID\> of 20 it leaves max. 18 characters for "|center|" ("gnl|center|" is not used by `tbl2asn` for the LOCUS identifier).

1. So for **--compliant**, if I'm not mistaken today ;-), line [408](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L408) should be changed to (number 13 comes from "contig_00000X", `$ncontig`):
    ```Perl
    my $contig_name_len = length($contigprefix) + 13;
    ```
 Also $contig_name_len is initialised twice in lines [406-408](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L406-408). Line [406](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L406) can be removed.

2. Lines [425-427](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L425-427) should be changed to (number 21 comes from "gnl|$centre|", the 18 from above plus 3):
    ```Perl
    if ((!$centre && length($seq->id) > $MAXCONTIGIDLEN) || ($centre && length($seq->id) > $MAXCONTIGIDLEN + 21)) {
        msg("Contig ID must <= $MAXCONTIGIDLEN chars long: ".$seq->id) if (!$centre);
        my $idlen = $MAXCONTIGIDLEN + 21;
        msg("Contig ID must <= $idlen chars long: ".$seq->id) if ($centre);
        err("Please rename your contigs or use --centre XXX to generate clean contig names.");
```

**Comment by tseemann** [comment]
I think I made a bad decision with regard to making .GBK files correct. The NCBI spec for Genbank LOCUS lines seems to be 16 chars, but for submission to NCBI they can be longer. I am becoming quite confused! I am considering dropping the tbl2asn dependency and writing my own Genbank files.

**Comment by aleimba** [comment]
Hi @tseemann,
yes, seems another NCBI "confusion" strategy. Would be one possibility to kick `tbl2asn`, especially since it cannot cope with lots of CDS apparently (we had the same issue as #65).
However, I still like the convenience to get *.sqn* files from Prokka. I'm wondering how many people use these directly for submission.
Would it be too strict to enforce the **contig_ID** length to 20?

**Comment by john-nash** [comment]
Ok... I'm lost.  My NCBI locustag is LFZxx (where xx is a bunch of one or two digit numbers).  I made aleimba's recommended changes above (deleted line 406, changed line 408, altered lines 425-427). My command line is: 

$ /usr/molbin/prokka-1.11/bin/prokka --compliant --centre PHAC-LFZ --locustag LFZ22  --outdir whatever --force ST403_final.fasta 

I get: 
[12:26:52] Genbank contig IDs are 28 chars, must be <= 20. Prefix is: LFZ22_

Am I thick?

**Comment by aleimba** [comment]
hm, weird. Your command worked for me. Did you include those changes in v1.11?
```bash
$ ./bin/prokka --compliant --centre PHAC-LFZ --locustag LFZ22 --outdir whatever --force test.fasta 
[20:18:06] This is prokka 1.11
```

Here's what my local version looks like (corresponds to lines [405-429](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L405-429) in the current GitHub `prokka` script):
```Perl
$contigprefix .= '_' if $contigprefix;
if ($compliant) {
  my $contig_name_len = length($contigprefix) + 13;
  if ($contig_name_len > $MAXCONTIGIDLEN) {
    err("Genbank contig IDs are $contig_name_len chars, must be <= $MAXCONTIGIDLEN. Prefix is: $contigprefix");
  }
}

while (my $seq = $fin->next_seq) {
  if ($seq->length < $mincontiglen) {
    msg("Skipping short (<$mincontiglen bp) contig:",$seq->display_id);
    next;
  }
  $ncontig++;
  # http://www.ncbi.nlm.nih.gov/genomes/static/Annotation_pipeline_README.txt
  # leave contigs names as-is unless they are in --compliant mode or want --centre set
  if ($centre) {  
    $seq->id( sprintf "gnl|$centre|${contigprefix}contig%06d", $ncontig );
  }
  if ((!$centre && length($seq->id) > $MAXCONTIGIDLEN) || ($centre && length($seq->id) > $MAXCONTIGIDLEN + 21)) {
    msg("Contig ID must <= $MAXCONTIGIDLEN chars long: ".$seq->id) if (!$centre);
    my $idlen = $MAXCONTIGIDLEN + 21;
    msg("Contig ID must <= $idlen chars long: ".$seq->id) if ($centre);
    err("Please rename your contigs or use --centre XXX to generate clean contig names.");
  }
  my $s = $seq->seq;
```

**Comment by john-nash** [comment]
Mea culpa: I did not type line 405 in correctly.

my $contig_name_len = length($contigprefix) + 13;

Thank you so much.

**Comment by aleimba** [comment]
if we go forward with this, I guess the error message in line [410](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L410) could also be more informative, something like:
```Perl
err("Genbank contig IDs are $contig_name_len chars, must be <= $MAXCONTIGIDLEN. Prefix is '$contigprefix', locus_tag has to be <= 6.");
```

This is very strict for the locus_tag. Actually, in our lab we use shorter contig numerations, e.g. "XXXX_c001" etc.. Maybe the seq ID could also be shortened to make more room for the locus_tag (line [423](https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L423))?
```Perl
$seq->id( sprintf "gnl|$centre|${contigprefix}c%06d", $ncontig );
```

**Comment by tseemann** [comment]
You cane make MAXCONTIGIDLENGTH as big as you want. The only real restriction is in generating valid .GBK file. The GFF has no restriction. The SQN has a restriction that is much bigger than GBK (hence my confusion).

**Comment by aleimba** [comment]
yep, only looked up GENBANK. Still "contig000000X" could be shortened to "c00000X" to make more room?

**Comment by cometsong** [comment]
Makes sense to modify the max contain id length as you mentioned, however we've got this app installed on our cluster server and I don't have write access to the file.  

The contig id's in the assembly I'm working with are like "*NODE_77_length_128_cov_586_ID_153*".

Options I have are 1) install it locally and mod the max length, to be used whenever I run across this error; or 2) individually mod the actual fasta file headers i'm starting with **if** any of their contig id's are that long.

Does it make sense to make a local copy of the prokka script itself and then direct it to find all the dependency software on the PATH?

**Comment by tseemann** [comment]
@cometsong You can make a copy of prokka, say "prokka2" in the same bin directory and modify it and everything will just work, because it finds all the paths relative to the script location. It even works if you symlink it into somewhere else like /usr/local.

**Comment by cometsong** [comment]
Yeah that makes sense, of course.
I think I will copy from the current directory to a local personal one and then mod all the paths that the prokka script searches for the 'binaries' and 'db' folder. As I'm not admin on the cluster, I don't have write access to any other folders on that server except the user dir and a usergroup data dir.
This works.  I'll mod the script to make it more malleable for location and other variable values.
*Thanks!*

**Comment by tseemann** [comment]
You should consider using the Brew package system.  It can all be installed in your $HOME directory without root privileges. Prokka and all it's dependencies are in Brew too. It's no a perfect packagaing system, but it does empower the end user and remove reliance on the sysadmin powers!

It is available on Mac (http://brew.sh/) and Linux (https://github.com/Homebrew/linuxbrew)
