### ISSUE TITLE
Dodgy modified product

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#78]
[13:23:14] Modify product: Conserved virulence factor B => hypothetical protein

**Comment by mcnelsonphd** [comment]
I've been meaning to submit my own issues with the modification process, but I'll just tack on with this one since it's been noted. The RegEX is definitely being too aggressive as the following examples demonstrate:

 Transcription termination/antitermination protein NusA => hypothetical protein
 Transcription termination/antitermination protein NusG => hypothetical protein
 Transcription termination factor Rho  => hypothetical protein

Also, anything with homolog in the name appears to be made hypothetical, whereas the more normal convention would be to say like-protein

 Co-chaperone protein HscB homolog  => hypothetical protein
 DNA repair protein RadA homolog  => hypothetical protein

Most of this stems from the reference databases, so I've made some changes there to clean up product names and it seems like that might be the better way to go for some of these issues, or to have an array of product names that the RegEx wants to modify but you check against first to prevent that from occurring.

Great software though, appreciate all the hard work.

**Comment by tseemann** [comment]
I'm pretty sure I fixed this at some point in the last 3 years.
